/* 
    Mudança aluguel não é mais chave secundária
    LOCAL = {NFANTASIA, AREA, LOTACAO, ALUGUEL, ENDEREÇO, TELEFONE, PROPRIETARIO}
*/
CREATE TABLE LOCAL (
    NFANTASIA VARCHAR2(20) NOT NULL,
    AREA VARCHAR2(10) NOT NULL,
    LOTACAO NUMBER(5),
    ALUGUEL VARCHAR2(10) NOT NULL,
    ENDERECO VARCHAR2(30) NOT NULL,
    TELEFONE CHAR(12),
    NPROPRIETARIO VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_LOCAL PRIMARY KEY(NFANTASIA)
);

/* 
    Mudança de dia/horario para Data e local agora Not Null
    EVENTO = {NRO, TEMA, DATA, DESC, LOCAL} 
*/
CREATE TABLE EVENTO (
    NRO NUMBER(10) NOT NULL,
    TEMA VARCHAR2(20) NOT NULL,
    DATA DATE NOT NULL,
    DESC VARCHAR2(100),
    LOCAL VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY(NRO),
    CONSTRAINT FK_EVENTO FOREIGN KEY(LOCAL) REFERENCES LOCAL(NFANTASIA) ON DELETE CASCADE
    /** TIPO ????**/
);

/*

*/
CREATE TABLE CERIMONIA (
    NRO NUMBER(10) NOT NULL,
    RELIGIAO VARCHAR2(20),
    MESTRE VARCHAR2(20),
    CONSTRAINT PK_CERIMONIA PRIMARY KEY(NRO),
    CONSTRAINT FK_CERIMONIA FOREIGN KEY(NRO) REFERENCES EVENTO(NRO) ON DELETE CASCADE
);

CREATE TABLE COLACAO (
    NRO NUMBER(10) NOT NULL,
    CONSTRAINT PK_COLACAO PRIMARY KEY(NRO),
    CONSTRAINT FK_COLACAO FOREIGN KEY(NRO) REFERENCES EVENTO(NRO) ON DELETE CASCADE
);

/* 
    LINKAR COM O FLORISTA DO ANTONIO DEPOIS
    NAO SEI O TIPO DE ORDEM DE SERVICO
*/
CREATE TABLE FESTA_CASAMENTO (
    NRO NUMBER(10) NOT NULL,
    FLORISTA VARCHAR2(20),
    CONSTRAINT PK_FESTA_CASAMENTO PRIMARY KEY(NRO),
    CONSTRAINT FK_FESTA_CASAMENTO FOREIGN KEY(NRO) REFERENCES EVENTO(NRO) ON DELETE CASCADE,
    CONSTRAINT FK_FLORISTA FOREIGN KEY(FLORISTA) REFERENCES FLORISTA(ORDEMDESERVICO) ON DELETE CASCADE
);

/*
    LINKAR COM A ESTILIZAÇÃO DEPOIS
    NAO SEI O TIPO DE ORDEM DE SERVICO
*/
CREATE TABLE FESTA_FORMATURA (
    NRO NUMBER(10) NOT NULL,
    ESTILIZAÇÃO VARCHAR2(20),
    CONSTRAINT PK_FESTA_FORMATURA PRIMARY KEY(NRO),
    CONSTRAINT FK_FESTA_FORMATURA FOREIGN KEY(NRO) REFERENCES EVENTO(NRO) ON DELETE CASCADE,
    CONSTRAINT FK_ESTILIZACAO FOREIGN KEY(ESTILIZACAO) REFERENCES ESTILIZACAO(ORDEMDESERVICO) ON DELETE CASCADE
);

CREATE TABLE COMISSAO (
    NOME VARCHAR2(20) NOT NULL,
    TELEFONE CHAR(12),
    EMAIL VARCHAR2(30),
    CONSTRAINT PK_COMISSAO PRIMARY KEY(NOME)
);

CREATE TABLE FORMATURA (
    COMISSAO VARCHAR2(20) NOT NULL,
    FESTA NUMBER(10) NOT NULL,
    COLACAO NUMBER(10),
    CONSTRAINT PK_FORMATURA PRIMARY KEY(COMISSAO, FESTA),
    CONSTRAINT FK_COMISSAO FOREIGN KEY(COMISSAO) REFERENCES COMISSAO(NOME) ON DELETE CASCADE,
    CONSTRAINT FK_FFORMATURA FOREIGN KEY(FESTA) REFERENCES FESTA_FORMATURA(NRO) ON DELETE CASCADE,
    CONSTRAINT FK_CFORMATURA FOREIGN KEY(COLACAO) REFERENCES COLACAO(NRO) ON DELETE CASCADE
);

/*
    lINKAR COM O VITOR DEPOIS
*/
CREATE TABLE CASAMENTO (
    NOIVX CHAR(11) NOT NULL,
    FESTA NUMBER(10) NOT NULL,
    CERIMONIA NUMBER(10),
    CONSTRAINT PK_CASAMENTO PRIMARY KEY(NOIVX, FESTA),
    CONSTRAINT FK_NOIVX FOREIGN KEY(NOIVX) REFERENCES NOIVX(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_FCASAMENTO FOREIGN KEY(FESTA) REFERENCES FESTA_CASAMENTO(NRO) ON DELETE CASCADE,
    CONSTRAINT FK_CCASAMENTO FOREIGN KEY(CERIMONIA) REFERENCES CERIMONIA(NRO) ON DELETE CASCADE
);


/* ================ TABELAS RELACIONADAS A PESSOAS ================ */
CREATE TABLE PESSOA (
    CPF   CHAR(14) NOT NULL,
    NOME  VARCHAR(30) NOT NULL,
    --TIPO  VARCHAR() NOT NULL,
    
    CONSTRAINT PK_PESSOA PRIMARY KEY (CPF)
    --CONSTRAINT CK_PESSOA_TIPO CHECK () 
);

CREATE TABLE NOIVO (
    CPF   CHAR(14) NOT NULL,
    TELEFONE NUMBER,  -- NOT NULL ??
    
    CONSTRAINT PK_NOIVO PRIMARY KEY (CPF),
    CONSTRAINT FK_NOIVO FOREIGN KEY (CPF)
        REFERENCES PESSOA (CPF) 
        ON DELETE CASCADE
);

CREATE TABLE FORMANDO (
    CPF   CHAR(14) NOT NULL,
    CURSO  VARCHAR(30),
    INSTITUICAO VARCHAR(30),
    
    CONSTRAINT PK_FORMANDO PRIMARY KEY (CPF),
    CONSTRAINT FK_FORMANDO FOREIGN KEY (CPF)
        REFERENCES PESSOA (CPF) 
        ON DELETE CASCADE
);

CREATE TABLE FUNCIONARIO (
    CPF   CHAR(14) NOT NULL,
    CARGO VARCHAR(30),
    ENDERECO VARCHAR(30),
    NROCT CHAR(13) NOT NULL, -- CATEIRA DE TRABALHO (XX.XXXXX.XX-X)
    SALARIO NUMBER,
    --SERVICO 
    
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),
    CONSTRAINT FK1_FUNCIONARIO FOREIGN KEY (CPF)
        REFERENCES PESSOA (CPF) 
        ON DELETE CASCADE,
    --CONSTRAINT FK2_FUNCIONARIO FOREIGN KEY (SERVICO)
    --    REFERENCES PESSOA (ORDEMSERVICO) 
    --    ON DELETE CASCADE,
    CONSTRAINT UK_FUNCIONARIO UNIQUE(NROCT)   
);