CREATE TABLE FUNCIONARIO{
	CPF CHAR(14) NOT NULL, -- xxx.xxx.xxx-xx
	CARGO CHAR(13),
	ENDERECO VARCHAR2(),
	CT CHAR(14),
	SALARIO FLOAT(),
	ORDEM_SERVICO NUMBER(),

	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CPF),
	CONSTRAINT FK_CPF_FUNCIONARIO FOREIGN KEY(CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE,
	CONSTRAINT FK_ORDEM_SERVICO_FUNCIONARIO FOREIGN KEY(ORDEM_SERVICO) REFERENCES SERVICO(ORDEM_SERVICO) ON DELETE CASCADE, -- NAO FAZ MUITO SENTIDO SER ON DELETE CASCADE
	CONSTRAINT CK_CT CHECK(REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{5}\.[0-9]{2}\-[0-9]{1}'),
	CONSTRAINT CK_CPF CHECK(REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')
};

CREATE TABLE SERVICO{
	ORDEM_SERVICO NUMBER(),
	PRECO FLOAT(),
	TIPO CHAR(11), 

	CONSTRAINT PK_SERVICO PRIMARY KEY(ORDEM_SERVICO),
	CONSTRAINT CK_TIPO CHECK(TIPO IN ('ESTILIZACAO', 'FLORISTA', 'SEGURANCA', 'DECORACAO', 'BUFFET'))
};

------------------------------------------------------------------------------------

CREATE TABLE ESTILIZACAO{
	ORDEM_SERVICO NUMBER(),
	PACOTE CHAR(8)
	MODELO VARCHAR2()
	QUANTIDADE NUMBER(4) -- MAXIMO DE 9999 CAMISETAS


	CONSTRAINT PK_ESTILIZACAO PRIMARY KEY(ORDEM_SERVICO),
	CONSTRAINT FK_ORDEM_SERVICO_ESTILIZACAO FOREIGN KEY(ORDEM_SERVICO) REFERENCES SERVICO(ORDEM_SERVICO) ON DELETE CASCADE,
	CONSTRAINT CK_PACOTE CHECK(TIPO IN ('BASICO', 'COMPLETO')
};

---------------------------------FLORISTA-------------------------------------------

CREATE TABLE FLORISTA{
	ORDEM_SERVICO NUMBER(),

	CONSTRAINT PK_FLORISTA PRIMARY KEY(ORDEM_SERVICO),
	CONSTRAINT FK_ORDEM_SERVICO_FLORISTA FOREIGN KEY(ORDEM_SERVICO) REFERENCES SERVICO(ORDEM_SERVICO) ON DELETE CASCADE
};

CREATE TABLE ARRANJO{
	ORDEM_SERVICO NUMBER(),
	NRO_ARRANJO NUMBER()

	CONSTRAINT PK_FLORISTA PRIMARY KEY(ORDEM_SERVICO, NRO_ARRANJO),
	CONSTRAINT FK_ORDEM_SERVICO_ARRANJO FOREIGN KEY(ORDEM_SERVICO) REFERENCES FLORISTA(ORDEM_SERVICO) ON DELETE CASCADE
};

CREATE TABLE ESPECIES{
	ORDEM_SERVICO NUMBER(),
	NOME_ESPECIE VARCHAR2(),

	CONSTRAINT PK_FLORISTA PRIMARY KEY(ORDEM_SERVICO, NOME_ESPECIE),
	CONSTRAINT FK_ORDEM_SERVICO_ESPECIES FOREIGN KEY(ORDEM_SERVICO) REFERENCES FLORISTA(ORDEM_SERVICO) ON DELETE CASCADE
};

-------------------------------------------------------------------------------------

CREATE TABLE SEGURANCA{
	ORDEM_SERVICO NUMBER(),
	NIVEL CHAR(11),

	CONSTRAINT PK_SEGURANCA PRIMARY KEY(ORDEM_SERVICO),
	CONSTRAINT FK_ORDEM_SERVICO_SEGURANCA FOREIGN KEY(ORDEM_SERVICO) REFERENCES SERVICO(ORDEM_SERVICO) ON DELETE CASCADE,
	CONSTRAINT CK_NIVEL CHECK(TIPO IN ('BASICO', 'SOFISTICADO')
};

---------------------------------DECORACAO-------------------------------------------

CREATE TABLE DECORACAO{
	ORDEM_SERVICO NUMBER(),
	TEMA VARCHAR2(),

	CONSTRAINT PK_FLORISTA PRIMARY KEY(ORDEM_SERVICO),
	CONSTRAINT FK_ORDEM_SERVICO_FLORISTA FOREIGN KEY(ORDEM_SERVICO) REFERENCES SERVICO(ORDEM_SERVICO) ON DELETE CASCADE,
	
};

CREATE TABLE OBJETO{
	ORDEM_SERVICO NUMBER(),
	NOME VARCHAR2(),
	QUANTIDADE NUMBER(),

	CONSTRAINT PK_OBJETO PRIMARY KEY(ORDEM_SERVICO, NOME),
	CONSTRAINT FK_ORDEM_SERVICO_OBJETO FOREIGN KEY(ORDEM_SERVICO) REFERENCES DECORACAO(ORDEM_SERVICO) ON DELETE CASCADE
};

---------------------------------BUFFET-------------------------------------------

CREATE TABLE BUFFET{
	ORDEM_SERVICO NUMBER()

	CONSTRAINT PK_BUFFET PRIMARY KEY(ORDEM_SERVICO),
	CONSTRAINT FK_ORDEM_SERVICO_BUFFET FOREIGN KEY(ORDEM_SERVICO) REFERENCES SERVICO(ORDEM_SERVICO) ON DELETE CASCADE
};

CREATE TABLE CARDAPIO{
	ORDEM_SERVICO NUMBER(),
	NOME VARCHAR2(),
	INGREDIENTES VARCHAR2(),
	QUANTIDADE NUMBER(),

	CONSTRAINT PK_CARDAPIO PRIMARY KEY(ORDEM_SERVICO, NOME),
	CONSTRAINT FK_ORDEM_SERVICO_CARDAPIO FOREIGN KEY(ORDEM_SERVICO) REFERENCES BUFFET(ORDEM_SERVICO) ON DELETE CASCADE
};

CREATE TABLE BEBIDA{
	ORDEM_SERVICO NUMBER(),
	NOME VARCHAR2(),
	QUANTIDADE NUMBER(),

	CONSTRAINT PK_BEBIDA PRIMARY KEY(ORDEM_SERVICO, NOME),
	CONSTRAINT FK_ORDEM_SERVICO_BEBIDA FOREIGN KEY(ORDEM_SERVICO) REFERENCES BUFFET(ORDEM_SERVICO) ON DELETE CASCADE
};
